import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  modalContainer: { flex: 1, backgroundColor: '#0c0a09', paddingHorizontal: 20 },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: '#292524',
  },
  title: { color: '#ffffff', fontSize: 22, fontWeight: '900' },
  subTitle: { color: '#fbbf24', fontSize: 13, fontWeight: '700', marginTop: 2 },
  closeBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#292524',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeBtnText: { color: '#a8a29e', fontSize: 16, fontWeight: '800' },
  scrollList: { paddingVertical: 20, gap: 12 },
  pillCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1c1917',
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#292524',
  },
  checkCircle: {
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 2,
    borderColor: '#78716c',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  checkCircleTaken: { backgroundColor: '#10b981', borderColor: '#10b981' },
  checkMark: { color: '#ffffff', fontSize: 14, fontWeight: '900' },
  info: { flex: 1 },
  name: { color: '#ffffff', fontSize: 16, fontWeight: '700' },
  nameTaken: { color: '#78716c', textDecorationLine: 'line-through' },
  dosage: { color: '#a8a29e', fontSize: 13, marginTop: 2 },
  voiceBtn: {
    backgroundColor: '#3b2507',
    borderWidth: 1,
    borderColor: '#d97706',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  voiceBtnText: { color: '#fde047', fontSize: 12, fontWeight: '700' },
});
